Aircraft
^Albion
^Alamein
^Alphington
^Altona
^Armadale
^Ashburton
^Aspendale
^Ascot Vale
^Anstey
^Auburn
^Batman
^Bayswater
^Brighton Beach
^Blackburn
^Balaclava
^Belgrave
^Bell
^Bentleigh
^Berwick
^Beaconsfield
^Bittern
^Burnley
^Broadmeadows
^Bonbeach
^Boronia
^Box Hill
^Burwood
^Brunswick
^Baxter
^Camberwell
^Carrum
^Cranbourne
^Canterbury
^Croydon
^Caulfield
^Clifton Hill
^Chatham
^Clayton
^Carnegie
^Coburg
^Crib Point
^Chelsea
^Cheltenham
^Collingwood
^Croxton
^Darebin
^Diamond Creek
^Dennis
^Darling
^Dandenong
^Eaglemont
^East Camberwell
^Edithvale
^Elsternwick
^Eltham
^East Malvern
^Epping
^East Richmond
^Essendon
^Fawkner
^Flemington Bridge
^Fairfield
^Flagstaff
^Frankston
^Flinders Street
^Footscray
^Ferntree Gully
^Gardiner
^Glenbervie
^Glenferrie
^Glenhuntly
^Ginifer
^Glen Iris
^Gowrie
^Greensborough
^Glenroy
^Gardenvale
^Glen Waverley
^Hampton
^Hawthorn
^Hurstbridge
^Hoppers Crossing
^Heidelberg
^Heyington
^Highett
^Hawksburn
^Hallam
^Heathmont
^Holmesglen
^Hastings
^Heatherdale
^Hughesdale
^Huntingdale
^Hartwell
^Ivanhoe
^Jacana
^Jolimont
^Jordanville
^Jewell
^Kananook
^Kensington
^Keon Park
^Keilor Plains
^Kooyong
^Laburnum
^Lalor
^Laverton
^Lilydale
^Leawarra
^Mont Albert
^Macaulay
^Malvern
^Middle Brighton
^Macleod
^Melbourne Central
^Mitcham
^McKinnon
^Mentone
^Merri
^Middle Footscray
^Moreland
^Mooroolbark
^Montmorency
^Mordialloc
^Moonee Ponds
^Merinda Park
^Murrumbeena
^Moorabbin
^Morradoo
^Mount Waverley
^Merlynston
^North Brighton
^Northcote
^Newmarket
^North Melbourne
^Noble Park
^Newport
^North Richmond
^Narre Warren
^Nunawading
^North Williamstown
^Oakleigh
^Officer
^Oak Park
^Ormond
^Parliament
^Patterson
^Parkdale
^Pakenham
^Prahran
^Preston
^Pascoe Vale
^Flemington Racecourse
^Regent
^Reservoir
^Ripponlea
^Riversdale
^Richmond
^Rosanna
^Royal Park
^Rushall
^Ruthven
^Ringwood
^Ringwood East
^St. Albans
^Watergardens
^Seaford
^Seddon
^Showgrounds
^Seaholme
^Surrey Hills
^Sandringham
^South Kensington
^Strathmore
^Sandown Park
^Springvale
^Spotswood
^Southern Cross
^Stony Point
^Sunshine
^Somerville
^Syndal
^South Yarra
^Tyabb
^Thornbury
^Tecoma
^Tooronga
^Toorak
^Tottenham
^Thomastown
^Upfield
^Upper Ferntree Gully
^Upwey
^Victoria Park
^Watsonia
^Williamstown Beach
^Werribee
^West Footscray
^Williamstown
^Windsor
^West Richmond
^Willison
^Westgarth
^Westall
^Westona
^Wattle Glen
^Yarraman
^Yarraville 
^Altona Junction
^Burnley Stabling Sidings
^Richmond Junction
^Franklin Street
^General Motors
^Lynbrook Loop
^Spencer St. Layby Sidings
^Long Island
^Long Island Junction
^MMacaulay Light Repair Centre
^Macaulay Stabling Sidings
^Melbourne Yard Stabling Sidings
^North Melbourne Stabling Sidings
^Newport Workshops
^Viaduct Junction 