[HITACHI] heading [DIRECTION] at [LOCATION] at about [TIME], and another unknown at flinders at about 3 on an [LOCATION_ALT]
^Spotted [HITACHI] at [LOCATION] at [TIME] today going to [LOCATION] even though the desto said Alamein!
^[HITACHI] ran a [DIRECTION] [LOCATION_ALT] through [LOCATION] at [TIME].
^Dear All[]
[HITACHI] ran the [TIME] DOWN [LOCATION_ALT] & 18:41 [DIRECTION] [LOCATION] [PERIOD].[]
Kind Regards[/]
[USER]
^Just saw [HITACHI] departing [LOCATION] this morning, at [TIME]. 
^[HITACHI] [LEAD] the [TIME] [DIRECTION] [LOCATION] so would have led the 16.02 down.
^An unidentified set on platform 4 for the [TIME] [LOCATION].
^Saw Hitachi no. [HITACHI] depart on the [TIME] [LOCATION] to [LOCATION_ALT] [PERIOD]. 
^[HITACHI] spotted at [LOCATION] at [TIME] this [PERIOD].
^[HITACHI] was on the [GROUP] group this [PERIOD] at [LOCATION] around [TIME].
^[HITACHI] ran empty along the [DIRECTION] track to [LOCATION] this morning. It would have departed FSS around [TIME]
^[HITACHI] led this [PERIOD]s [TIME] [DIRECTION] [LOCATION] which means that (subject to rostering) it may well turn up on tail of the 07.03 up Frankston express tomorrow.
^[HITACHI] ran the [TIME] [LOCATION] super express this [PERIOD]. []
[USER]
^[HITACHI] was on the the [TIME] [LOCATION] tonight, with another set noted on the [DIRECTION] Caulfield Through crossing Cremorne Bridge at 17.10.
^Passed a silver at [LOCATION] this [PERIOD] at 3:45pmish. I think it would have been the 2:59 Frankston from Flinders Street running about 10 minutes late because I saw another Frankston on platform 2 at Moorabbin a few minutes later.
[]Also saw another silver around North Melbourne about [TIME] I think if my memory can recall... 
^[TIME] [LOCATION] tonight pulled out of Flinders St and ran round the viaduct about 100m ahead of a [DIRECTION] [GROUP] Group service worked by a Hitachi.
[]Sorry I wasn't able to confirm either the set or the working involved on this occasion.
^[HITACHI] headed the [TIME] [DIRECTION] [LOCATION] this morning.
^[HITACHI] was stabled in [LOCATION] at [TIME]
[][HITACHI] was stabled in [LOCATION] at 12!
^Didn't have time to add yesterday, [HITACHI] lead the early morning [TIME] train to [LOCATION] from Flinders Street, viewed from the Iramoo X'Trapolis set, 852M.
^[TIME] down / 17.24 up [LOCATION] were Hitachi worked again tonight. Sorry I wasn't able to pick the number as we crossed the [DIRECTION] at speed in the dark!
^[HITACHI] spotted at [LOCATION] headed to Alamein around [TIME] this [PERIOD].
^Another Hitachi on a [DIRECTION] [LOCATION], if one can believe the desto roll at East Richmond about five minutes later.
^3 silvers at [LOCATION] this [PERIOD], I guess around [TIME] was when I went by.
^I saw [HITACHI] heading down to [LOCATION] on Monday 25th (it would have been scheduled to depart FSS at [TIME]).
[]At the time, I hadn't seen any reports of [HITACHI] being sighted since it left Newport. I now see that it was sighted on the northern group on the Friday before.
^On Monday, [HITACHI] came [DIRECTION] from [LOCATION] arriving FSS at 17:41 and departing for Pakenham again at [TIME]. On Tuesday, it came up from Pakenham arriving FSS at 8:43.
^An unidentified Hitachi came [DIRECTION] from [LOCATION] on Tuesday arriving FSS at [TIME].
^[HITACHI] ran the [TIME] [DIRECTION] [LOCATION] yesterday.
