I saw that set as well at [LOCATION] about [TIME].
^It must have run a later service, I saw it at [LOCATION] at [TIME] today going to [LOCATION].
^It must have spent a bit of time on the [GROUP] group, I saw it at [LOCATION] around [TIME].
^You must have caught the same train I did - I jumped on at [LOCATION].
^I caught that set from [LOCATION] to [LOCATION_ALT] about [TIME].
^I saw that set stabled later on in the day at [LOCATION].
^So that's where it went - I saw it about [TIME] at [LOCATION].
^I was wondering where that set was going - it flashed past me in the opposite direction on my way home.
^D'oh, knew I should've left work on time!
^It had to be on one of those ... glad it wan't the [TIME]
^Quite possibly - it should be possible to tell which line the train is on when it comes around the viaducts but not being that close my eyes might have been mistaken.
^I was on that set.
